kind: Service
apiVersion: v1
metadata:
  name: mythicalmysfits-service-canary
spec:
  type: NodePort
  selector:
    app: mythicalmysfits
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8081

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mythicalmysfits-deployment-canary
  labels:
    app: mythicalmysfits
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mythicalmysfits
      track: canary
  template:
    metadata:
      labels:
        app: mythicalmysfits
        track: canary
    spec:
      containers:
      - name: mythicalmysfits
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
