
kind: Service
apiVersion: v1
metadata:
  name: mythicalmysfits-service
spec:
  selector:
    app: mythicalmysfits
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080


---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /mysfits
spec:
  rules:
  - http:
      paths:
      - path: /mysfits
        backend:
          serviceName: mythicalmysfits-service
          servicePort: 8080

---  

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mythicalmysfits-deployment
  labels:
    app: mythicalmysfits
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mythicalmysfits
      track: stable
  template:
    metadata:
      labels:
        app: mythicalmysfits
        track: stable
    spec:
      containers:
      - name: mythicalmysfits
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
